apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: account-app
    spec:
      containers:
        - name: account-app
          image: anil9848/account-app:latest
          ports:
            - containerPort: 80