apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: acc-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: acc-service
    spec:
      containers:
        - name: acc-service
          image: anil9848/acc-service:latest
          ports:
            - containerPort: 80
