apiVersion: v1
kind: Service
metadata:
  labels:
    name: account-application
  name: account-application
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8082
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8084



  selector:
    app: account-application
  type: LoadBalancer